---
- hosts: tag_site-b
  become: yes
  roles:
    - role: pki
      vars:
        common_name: server1
        clients:
          - client1
    - role: openvpn
      vars:
        type: server
        server_network: 10.1.0.0 255.255.255.0
        client_networks:
          client1:
            network: 10.0.0.0 255.255.255.0
  tasks:
    - name: Fetch the client cert from the servers
      run_once: yes
      fetch: src=/etc/openvpn/{{item}} dest=buffer/ flat=yes
      with_items:
        - client1.key
        - client1.crt
        - ca.crt
        - ta.key
- hosts: tag_site-a
  become: yes
  tasks:
    - name: Copy the client certs
      copy:
        src: buffer/{{item}}
        dest: /etc/openvpn/
        owner: root
        group: root
        mode: "600"
      with_items:
        - client1.key
        - client1.crt
        - ca.crt
        - ta.key
    - name: Fetch the socks ssh public key
      run_once: yes
      fetch: src=/home/socks/.ssh/id_rsa.pub dest=buffer/ flat=yes
- hosts: tag_socks
  become: yes
  roles:
    - role: socks
      name: Setup the server side of the socks proxy
      vars:
        type: server
        key: "{{ lookup('file', 'buffer/id_rsa.pub') }}"
- hosts: tag_site-a
  become: yes
  roles:
    - role: socks
      vars:
        vps: "{{ hostvars['socks-proxy']['gce_public_ip'] }}"
        user_name: socks
        type: client
        port: 8000
    - role: openvpn
      vars:
        type: client
        client_name: client1
        server_name: "{{ hostvars['openvpn-site-b']['gce_public_ip'] }}"
        socks_port: 8000
