---
- hosts: tag_site-b
  become: yes
  roles:
    - role: pki
      vars:
        common_name: server1
        clients:
          - client1
    - role: openvpn
      vars:
        type: server
        server_network: 10.1.0.0 255.255.255.0
        client_networks:
          client1:
            network: 10.0.0.0 255.255.255.0
      tags: aqui
  tasks:
    - name: Fetch the client cert from the servers
      run_once: yes
      fetch: src=/etc/openvpn/{{item}} dest=buffer/ flat=yes
      with_items:
        - client1.key
        - client1.crt
        - ca.crt
        - ta.key
- hosts: tag_site-a
  become: yes
  tasks:
    - name: Copy the client certs
      copy:
        src: buffer/{{item}}
        dest: /etc/openvpn/
        owner: root
        group: root
        mode: "600"
      with_items:
        - client1.key
        - client1.crt
        - ca.crt
        - ta.key
  roles:
    - role: openvpn
      vars:
        type: client
        client_name: client1
        server_name: "{{ hostvars['openvpn-site-b-16d3']['gce_public_ip'] }}"
        port: 8000
      tags: aqui
    - role: socks
      vars:
        vps: "{{ hostvars['socks-proxy-16d3']['gce_public_ip'] }}"
        user_name: socks
        type: client
- hosts: tag_site-a
  become: yes
  tasks:
    - name: Fetch the socks ssh public key
      run_once: yes
      fetch: src=/home/socks/.ssh/id_rsa.pub dest=buffer/ flat=yes
- hosts: tag_socks
  become: yes
  roles:
    - role: socks
      vars:
        vps: "{{ hostvars['socks-proxy-16d3']['gce_public_ip'] }}"
        user_name: socks
        type: server
        key: "{{ lookup('file', 'buffer/id_rsa.pub') }}"
        port: 8000
      tags: aqui
